const en = {
  home: 'Home',
  about: 'About',
  projects: 'Projects',
  curProjects: 'Current Projects',
  contact: 'Contact',
  socials: 'Social Media',
  completed: 'Completed Projects',
  aboutMe: `Hello there, I'm Rizki Maulana. I'm a Web Developer from Jakarta, Indonesia. Have strong knowledge in HTML, CSS, and JavaScript. My expertise spans front-end and back-end development, leveraging modern technologies to bring ideas to life. I'm currently learning Chinese.`,
  menu: 'Menu',
  hello: 'Hello',
  name: 'Rizki Maulana',
  myNameIs: 'My name is Rizki Maulana  ',
  iAm: 'I am a',
  webDeveloper: 'Web Developer',
  slogan: `Crafting Code, Shaping Experiences – Let's Build the Web Together!`,
  dibimbing: 'Learning and mastering Algorithm and Web Programming with Javascript, HTML and CSS',
  dibimbing2: 'Learning Programming tools such as Visual Studio Code, Node.js and GitHub',
  dibimbing3: 'Learning JavaScript front-end framework such as React.js, Redux, Next.js',
  copyright: `Copyright © ${new Date().getFullYear()} Rizki Maulana. All rights reserved.`,
};

const zh = {
  home: '主页',
  about: '关于',
  projects: '项目',
  curProjects: '当前项目',
  contact: '联系',
  socials: '社交媒体',
  completed: '完成的项目',
  aboutMe: '你好，我是 Rizki Maulana, 一名来自印度尼西亚雅加达的网页开发者。我精通 HTML、CSS 和 JavaScript, 在前端和后端开发方面具有丰富的经验, 能够利用现代技术将创意变为现实。目前，我正在学习中文。',
  menu: '菜单',
  dibimbing: '学习和掌握算法和网页编程，使用JavaScript，HTML和CSS，让我们一起建造网页！',
  dibimbing2: '学习编程工具，如Visual Studio Code，Node.js和GitHub，让我们一起建造网页！',
  dibimbing3: '学习JavaScript前端框架，如React.js，Redux，Next.js，让我们一起建造网页！',
  hello: '你好',
  name: 'Rizki Maulana',
  myNameIs: '我的名字是 Rizki Maulana',
  iAm: '我是一个',
  webDeveloper: '前端开发者',
  slogan: '我正在学中文,你好 :)',
};

export { en, zh };
